version: '3.5'
services:
  pg-chinook:
    container_name: pg-chinook
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "pg-chinook-data:/var/lib/postgresql/data"
    networks:
      chinooknet:
        ipv4_address: 172.22.0.5
  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@example.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "8080:80"
    networks:
      - chinooknet
volumes:
  pg-chinook-data:
    external: true
networks:
  chinooknet:
    name: chinooknet
    ipam:
      config:
        - subnet: 172.22.0.0/24